# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

Se puede crear una lista a partir de un rango

In [3]:

lis = list(range(1,10))
arr = np.arange(1,10)
print("Lista: ", lis)
print("Array: ",arr)

Lista:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array:  [1 2 3 4 5 6 7 8 9]


En un Numpy podemos crear matrices pero en una lista de python no

In [5]:

a = np.arange(0,20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


A partir de una lista podemos crear un arreglo de numpy

In [16]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


------

Array de forma (n) <br>
Unidimensional. Una fila y "n" columnas

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Array de forma (1,n) <br>
Los valores se organizan en una fila y "n" columnas. Se acceden a los mismos mediente dos indices. Uno para las filas y otro para las columnas. (Siempre las filas primero)

In [12]:
b = np.array([[4,5,6]])
print(b)

[[4 5 6]]


Array de forma (n,1) <br>
Una columna y "n" filas. Se acceden a los mismos mediente dos indices. Uno para las filas y otro para las columnas. (Siempre las filas primero)

In [13]:
c = np.array([1,2,3,4,5]).reshape(5,1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento. <br>|| Notar que suma un valor a la cadena, pero mantiene la misma cantidad de valores que antes ||

In [19]:
# Array sin realizarle la suma
print(arreglo)

[1 2 3 4 5 6]


In [23]:
# Array realizandole la suma
arreglo + 1
print(arreglo)

[2 3 4 5 6 7]


In [25]:
# En el caso de la lista, efectivamente nos tira un error ya que no se puede hacer 
# esa operacion en las lista de Python

lista + 1

TypeError: can only concatenate list (not "int") to list

2. Elevar al cuadrado todos los elementos

In [26]:
arreglo ** 2

array([ 4,  9, 16, 25, 36, 49])

In [ ]:
lista ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

3. Sumar todos los elementos

In [27]:
print(arreglo.sum())


27


In [28]:
print(lista.sum())

AttributeError: 'list' object has no attribute 'sum'

Una manera para efectuar una suma en una lista de Python

In [30]:
n = 0
for e in lista:
    n = n + e
print(n)

16


In [36]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,"\n\n Shape =", arreglo.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

 Shape = (3, 6)


Transponer un array:

In [ ]:
array_1 = np.array([[1,2,3,4,5],[5,4,3,2,1]]).T
print(array_1,"\n","\n","Shape del array: ",array_1.shape)

[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]] 
 
 Shape del array:  (5, 2)


Otra manera de transponer

In [39]:
array_2 = np.array([[1],[2],[3],[4],[5],[5],[4],[3],[2],[1]])
print(array_2,"\n","\n","Shape del array: ",array_2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]] 
 
 Shape del array:  (10, 1)


In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [40]:
arreglo = np.arange(0,10)
arreglo2 = np.linspace(0,10,100)
print(arreglo,"\n\n\n",arreglo2)

[0 1 2 3 4 5 6 7 8 9] 


 [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798 

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [41]:
arreglo = np.arange(10,101)
mascara = ((arreglo % 3) == 0)

arreglo[mascara]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [ ]:
ceros = np.zeros((5,10))
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
ceros[[1,3],:] = 1
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
ceros[:,[2,7]] = 2
print(ceros)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]
