# Practice Class 3

## Numpy

In [1]:
import numpy as np

**Exercise 1**: Answer the following questions:
* What operations can be done on both a numpy array and a list? Give an example in a cell.
* What operations can be done on a Numpy array but NOT on a list? Explore some options and give an example in a cell.
* What is the difference between an array of the form -shape- (n,), (n,1) and (1,n)? They can create arrays to try to answer that question.

You can create a list from a range

In [11]:

lis = list(range(1,10))
arr = np.arange(1,10)
print("List: ", lis)
print("Array: ",arr)

List:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array:  [1 2 3 4 5 6 7 8 9]


In a Numpy array we can create matrices but in a python list we can't

In [3]:

a = np.arange(0,20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


From a list we can create a numpy array

In [14]:
list_ = [0,1,2,3,4,5]
array = np.array(list_)
print(list_)
print(array)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


------

Array of shape (n) <br>
one dimensional. One row and "n" columns

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Array of shape (1,n) <br>
The values are arranged in one row and "n" columns. They are accessed by means of two indexes. One for the rows and one for the columns. (Always the rows first)

In [6]:
b = np.array([[4,5,6]])
print(b)

[[4 5 6]]


Array of shape (n,1) <br>
One column and "n" rows. They are accessed by means of two indexes. One for the rows and one for the columns. (Always the rows first)

In [7]:
c = np.array([1,2,3,4,5]).reshape(5,1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]


Some things that can be done with arrays but not with lists:

1. Add the same element. <br>|| Note that it adds a value to the string, but keeps the same number of values as before ||

In [17]:
print(array)

[0 1 2 3 4 5]


In [18]:

array + 1
print(arreglo)

[0 1 2 3 4 5]


In [19]:
# In the case of the list, it effectively throws an error since it cannot be done
# that operation on python lists

list_ + 1

TypeError: can only concatenate list (not "int") to list

2. Square all elements

In [20]:
array ** 2

array([ 0,  1,  4,  9, 16, 25])

In [21]:
list_ ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

3. Add up all the elements

In [ ]:
print(array.sum())


27


In [22]:
print(list_.sum())

AttributeError: 'list' object has no attribute 'sum'

A way to perform a sum on a list in Python

In [24]:
n = 3
for e in list_:
    n = n + e
print(n)

18


In [26]:
array = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(array,"\n\n Shape =", array.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

 Shape = (3, 6)


Transpose an array:

In [27]:
array_1 = np.array([[1,2,3,4,5],[5,4,3,2,1]]).T
print(array_1,"\n","\n","Shape of the array: ",array_1.shape)

[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]] 
 
 Shape of the array:  (5, 2)


Another way to transpose

In [28]:
array_2 = np.array([[1],[2],[3],[4],[5],[5],[4],[3],[2],[1]])
print(array_2,"\n","\n","Shape of the array: ",array_2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [4]
 [3]
 [2]
 [1]] 
 
 Shape of the array:  (10, 1)


In [30]:
array = np.array([[1,2,3,4,5,6]])
print(array,'. Shape =', array.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [31]:
array = np.array([[1,2,3,4,5,6]]).T 
print(array,'. Shape =', array.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



**Exercise 2**:
* Write an array with integers from 0 to 9. Hint: arange
* Write an array with 100 equispaced numbers from 0 to 9. Hint: linspace

In [34]:
array = np.arange(0,10)
array_2 = np.linspace(0,10,100)
print(array,"\n\n\n",array_2)

[0 1 2 3 4 5 6 7 8 9] 


 [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798 

**Exercise 3**:
* Write an array with integers from 10 to 100 and select those that are divisible by 3<br>
Clue: mask

In [36]:
array = np.arange(10,101)
mask = ((array % 3) == 0)

array[mask]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Exercise 4**:
* Create an array of zeros from `shape` (5,10).
* Replace the second and fourth row with ones
* Replace the third and eighth columns with two (2).

In [38]:
zeros = np.zeros((5,10))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
zeros[[1,3],:] = 1
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
zeros[:,[2,7]] = 2
print(zeros)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]
